--- 
title: "Pop Model"
author: "Michael E. Colvin, and others..."
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
---




<!-- compile book

library(knitr)
bookdown::render_book("",
    output="bookdown::gitbook",
    output_dir = "C:/Users/mcolvin/Documents/projects/Pallid Sturgeon/Analysis/Pallid-Sturgeon-Population-Model/docs")

-->
# Preface {-}

*This is work in progress, results are provisional and subject to change.
Do not used or cite this material in any way*

## Structure of the book {-}


## Some stuff
 River bends, defined as a outer bend and crossover were used to 
simulate spatial dynamics. The location of individual Pallid Sturgeon 
were tracked during each time step and moved to a new bend, conditional 
on survival and previous bend location assuming a multinomial 
distirubtion as, 


Loc_{j,t+\delta t}~Multinomial(p_{I,.,t}


 Where varibles and indices are defined in table xx. The vector of 
probabilities $p_{I,.,t}$ predicts the probable location given the 
previous bend location. This approach to movement provided a flexible 
approach to modeling movement that can be readily related to management 
actions. Specifically, $p_{I,j,t} is an array of probabilities with each 
row summing to one forming a 12 transition matrices providing the 
probability of moving from bend $i$ to bend $j$. This array of 
probabilities provides a plugin location for movement. The diagonal 
represents the probability of remaining in the same reach, off diagonal 
elements represent downstream or upstream movements. 


## Management effects on movement
The effect of management actions on movement or drift of adult or larval 
Pallid Sturgeion respectively can be simulated by modifying monthly 
transition matrices. For example, suppose that adult Pallid Sturgeon 
migrate upstream given a flow or temperature cue. This directed movement 
can be simulated by specifying the probability of a fish moving to 
downstream bends equal to 0 and upstream bends greather than 0. 
Similarly, the effect of flow on free embryo drift can be simulated with 
increased downstream probabilities. 


$Y_{I,j,t+1}=\beta_0 + \beta_1 \cdot Q_{I,j,t}$ for i<=j
i>j = 0

Current model implementation requires an array of transitions for each 
timestep. Future model versions will attempt to reefing the linke 
between environmental covariates like flow such that a time series of 
predicted flows can be used as as inputs. The relationship between 
movement and varying covariates may take the form of a model prediction 
given previous location. For example, movement in terms of kilometers 
could be modeled 


$rkm_{t+1} = \beta_0 + \beta_1 \cdot Q + \beta_2 \cdot rkm_t + \beta_3 \cdot Q \cdot rkm_t + \sigma$.
   
The equation predicts how far, on average, a pallid sturgeon will move 
given an effect of flow and current location. The interaction term 
accounts for the effect of location (i.e., fish cannot move as far if 
they are near the uppermost bends). 


## Effects on survival
Modeling the effect of management actions on survival is specified by a 
logistic equation. Specifically, the base survivals are simulated using 
the equation 


$\Phi_{stage} = \frac{exp(\beta_0)}{1+exp(\beta_0)}$,

Where $\beta_0$ represents the expected survival on logit scale. For 
example, adult survival is expected 




## Allee effect


A FUNCTION THAT PRODUCES AN ALLEE
EFFECT MODIFYING GAMETE FERTILIZATAION
SUCCESS

```{r}
B0=0.49
B1=0.72
D<- seq(0:1000)
y<- B1*log(D)+B0
y<- exp(y)
plot(D,y,ylab="Fertilization success",
	xlab="Density (fish/rkm)")
```



