library(RODBC)
library(data.table)
library(maps)
library(rgeos)
library(maptools)
library(rgdal)
library(knitr)
library(R2jags)	
#library(knitrBootstrap)
library(rmarkdown)
library(plyr)
library(reshape)
library(reshape2)

library(distr)
